# Generated by Django 5.0.7 on 2024-08-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20220307_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos_post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
